code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._080_lint_build.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.editor.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.structure.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.typesystem.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/org.mpsqa.lint.generic.mpl
Enabled Checkable and ReuseCheckable scripts to have level of severity level: ERROR, WARNING, INFO
Changed in org.mpsqa.lint:
`org.mpsqa.lint.generic`: concept, editor and typesystem of Checkable and ReuseCheckable scripts.
=> mpsqa.lint: Add severity level to checkable scripts

code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.tests.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/org.mpsqa.lint.mps_lang.linters_library.msd
Adds a linter that checks whether all modules with tests are part of a build script and hence executed in continuous integration runs.
=> Implement linter for test modules not part of a build script

build.gradle, build/scripts/build_all_scripts.xml, code/languages/org.mpsqa.arch/.mps/migration.xml, code/languages/org.mpsqa.arch/languages/org.mpsqa.arch/models/org.mpsqa.arch.intentions.mps, code/languages/org.mpsqa.arch/solutions/test.org.mpsqa.arch/models/test.org.mpsqa.arch._010_simple_dependencies@tests.mps, code/languages/org.mpsqa.arch/solutions/test.org.mpsqa.arch/test.org.mpsqa.arch.msd, code/languages/org.mpsqa.clones/.mps/migration.xml, code/languages/org.mpsqa.clones/tests/test.org.mpsqa.clones.headless/models/_010_headless_runner_1@tests.mps, code/languages/org.mpsqa.clones/tests/test.org.mpsqa.clones.headless/test.org.mpsqa.clones.headless.msd, code/languages/org.mpsqa.clones/tests/test.org.mpsqa.clones/models/_000_infrastructure@tests.mps, code/languages/org.mpsqa.clones/tests/test.org.mpsqa.clones/models/_010_identical_java_statements@tests.mps, code/languages/org.mpsqa.clones/tests/test.org.mpsqa.clones/models/_020_overlapping_clones@tests.mps, code/languages/org.mpsqa.clones/tests/test.org.mpsqa.clones/models/_200_save_load_filter_clones@tests.mps, code/languages/org.mpsqa.clones/tests/test.org.mpsqa.clones/test.org.mpsqa.clones.msd, code/languages/org.mpsqa.deprecated/.mps/migration.xml, code/languages/org.mpsqa.deprecated/languages/org.mpsqa.deprecated/models/org.mpsqa.deprecated.typesystem.mps, code/languages/org.mpsqa.deprecated/tests/test.org.mpsqa.deprecated/models/test.org.mpsqa.deprecated._010_deprecation_tests@tests.mps, code/languages/org.mpsqa.deprecated/tests/test.org.mpsqa.deprecated/test.org.mpsqa.deprecated.msd, code/languages/org.mpsqa.mutant/.mps/migration.xml, code/languages/org.mpsqa.mutant/tests/test.org.mpsqa.mutant.demolang/models/test.org.mpsqa.mutant.demolang._010_smoke_tests@tests.mps, code/languages/org.mpsqa.mutant/tests/test.org.mpsqa.mutant.demolang/models/test.org.mpsqa.mutant.demolang._020_smoke_constraints_tests@tests.mps, code/languages/org.mpsqa.mutant/tests/test.org.mpsqa.mutant.demolang/test.org.mpsqa.mutant.demolang.msd, code/languages/org.mpsqa.testing/solutions/org.mpsqa.gentest.baseline/models/org.mpsqa.gentest.baseline.mps, code/languages/org.mpsqa.unused/.mps/migration.xml, code/languages/org.mpsqa.unused/languages/org.mpsqa.invisible_models.test_lang/models/org.mpsqa.invisible_models.test_lang.behavior.mps, code/languages/org.mpsqa.unused/languages/org.mpsqa.invisible_models.test_lang/org.mpsqa.invisible_models.test_lang.mpl, code/languages/org.mpsqa.unused/languages/org.mpsqa.invisible_models/models/org.mpsqa.invisible_models.behavior.mps, code/languages/org.mpsqa.unused/languages/org.mpsqa.invisible_models/org.mpsqa.invisible_models.mpl, gradle/wrapper/gradle-wrapper.properties
I'd like to use the linters in MPS-Extensions, that's why I need the migration to 2022.2. For MPS 2022.2 you require JBR 17. The newer versions of the MPS Gradle plugin contain a fix for this JBR version, that's why I have upgraded it.
=> Migrate to 2022.2

code/languages/org.mpsqa.lint/.mps/modules.xml, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/org.mpsqa.lint.generic.mpl, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.expressions.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.test/models/org.mpsqa.lint.test@tests.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.test/org.mpsqa.lint.test.msd, code/languages/org.mpsqa.mutant/tests/test.org.mpsqa.mutant.demolang/models/test.org.mpsqa.mutant.demolang._010_smoke_testcode.mps, code/languages/org.mpsqa.mutant/tests/test.org.mpsqa.mutant.demolang/models/test.org.mpsqa.mutant.demolang._020_smoke_constraints_testcode.mps
* Check allows to cast to `node<>`, or cast `null` to `node<SomeConcept>`.
* Tests for the check added, not running as part of the build (not on this branch, only on master).
=> lint: cast-to-node check now less restrictive (2021.3)

.github/workflows/build_mpsqa.yml, build.gradle, build/scripts/build_all_scripts.xml, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._000_all_scripts.mps, code/languages/org.mpsqa.clones/languages/org.mpsqa.clones.config/models/org.mpsqa.clones.config.structure.mps, code/languages/org.mpsqa.clones/solutions/org.mpsqa.clones.build/models/org.mpsqa.clones.build.mps, code/languages/org.mpsqa.clones/tests/test.org.mpsqa.clones.headless/models/_010_headless_runner_1@tests.mps, code/languages/org.mpsqa.clones/tests/test.org.mpsqa.clones.headless/models/clone_config_headless_01.mps, code/languages/org.mpsqa.clones/tests/test.org.mpsqa.clones.headless/test.org.mpsqa.clones.headless.msd, code/languages/org.mpsqa.lint/.mps/modules.xml, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/org.mpsqa.lint.generic.mpl, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.build/models/org.mpsqa.lint.build.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.build/org.mpsqa.lint.build.msd, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.expressions.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.test/models/org.mpsqa.lint.test@tests.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.test/org.mpsqa.lint.test.msd, code/languages/org.mpsqa.mutant/tests/test.org.mpsqa.mutant.demolang/models/test.org.mpsqa.mutant.demolang._010_smoke_testcode.mps, code/languages/org.mpsqa.mutant/tests/test.org.mpsqa.mutant.demolang/models/test.org.mpsqa.mutant.demolang._020_smoke_constraints_testcode.mps, settings.gradle.kts
This PR contains two changes:
* Modifying a linter to allow casting to `node<>` or casting `null` to `node<[any concept]>`.
* Cleaning up the build a bit and integrating tests into it.
=> Allow casts to node<>, integrate tests into the build

code/languages/org.mpsqa.arch/solutions/org.mpsqa.arch.pluginSolution/models/org.mpsqa.arch.pluginSolution.plugin.mps, code/languages/org.mpsqa.arch/solutions/org.mpsqa.arch.pluginSolution/org.mpsqa.arch.pluginSolution.msd, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._060_arch_build.mps
Because of licensing issues, we have to use the version of PlantUML that uses the EPL license.
=> Update PlantUML to version 2023.13 (ASL license)

code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.modules.mps
This means the migration check should work without having to have all the used languages compiled and loaded.
As a result, the migration check can be run before or concurrently with compilation.
=> lint: determine language version based on language module

code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._080_lint_build.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.nodes.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/org.mpsqa.lint.generic.linters_library.msd
- fixes https://github.com/mbeddr/mps-qa/issues/52
The linter had many false positives because only the children were checked and not the properties and references. Now we still have negative positives like some "empty" root nodes in the aspect models e.g. an empty type system rule. The issue is that they have children that are initialized in the constructor so we can't detect them. They should be could by the model checker though.
=> Linters: Improve root nodes without children linters

.gitignore, build/scripts/build_all_scripts.xml, code/languages/org.mpsqa.base/.mps/modules.xml, code/languages/org.mpsqa.base/solutions/org.mpsqa.base.build/models/org.mpsqa.base.build.mps, code/languages/org.mpsqa.base/solutions/org.mpsqa.base.build/org.mpsqa.base.build.msd, code/languages/org.mpsqa.build/.mps/libraries.xml, code/languages/org.mpsqa.build/solutions/org.mpsqa.build.allScripts/models/org.mpsqa.build.allScripts.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build.sandboxes/models/org.mpsqa.build.sandboxes.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build.sandboxes/org.mpsqa.build.sandboxes.msd, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._020_testing_build.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._030_clones_build.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._040_mutant_build.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._050_unused_build.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._060_arch_build.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._070_deprecated_build.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._080_lint_build.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._100_allInOne_build.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/org.mpsqa.build.msd, code/languages/org.mpsqa.testing/.mps/modules.xml, code/languages/org.mpsqa.testing/solutions/org.mpsqa.testing.build/models/org.mpsqa.testing.build.mps, code/languages/org.mpsqa.testing/solutions/org.mpsqa.testing.build/org.mpsqa.testing.build.msd, code/languages/org.mpsqa.testing/solutions/org.mpsqa.testing.tests.build/models/org.mpsqa.testing.tests.build.mps, code/languages/org.mpsqa.testing/solutions/org.mpsqa.testing.tests.build/org.mpsqa.testing.tests.build.msd
This is a prerequisite for adding a test for jacoco integration in the testing project.
This is a breaking change but should be easily fixed with Alt+Enter and adding dependencies on the new modules.
=> Separate build of base and testing

code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.models.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.performance_typesystem_rules.mps
models_in_same_project_with_same_IDs: re-wrote the linter "models_in_same_project_with_same_IDs" not to depend on MPS loading of models
Now we use low-level iteration through files and text reading API to get the model-id
=> lint: re-write linter "models_in_same_project_with_same_IDs"

code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.typesystem.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.util.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.modules.mps
The following PR adds a new helper `CyclicModuleDependenciesFromStartingPointHelper` class and a new linter `cyclic_module_dependencies_from_starting_point` that can be used to discover dependency cycles during development.
The starting module from which to look for cyclic dependencies needs to be specified.
A DFS traversal is used to look for cyclic dependencies and the linter stops at the first cycle along each path.
After solving a cycle, rerunning the linter can lead to new cycles being found by the traversal.
=> Cyclic dependencies find some

code/languages/org.mpsqa.base/solutions/org.mpsqa.base.errors_suppressor.pluginSolution/models/org.mpsqa.base.errors_suppressor.pluginSolution.plugin.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._080_lint_build.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/generator/templates/org.mpsqa.lint.generic.generator.templates@generator.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.behavior.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.editor.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.structure.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.typesystem.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/org.mpsqa.lint.generic.mpl, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.filesystem.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.meta.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.models.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.modules.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.nodes.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/org.mpsqa.lint.generic.linters_library.msd, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.runtime/models/org.mpsqa.lint.generic.runtime.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.runtime/org.mpsqa.lint.generic.runtime.msd, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.sandbox/models/org.mpsqa.lint.generic.sandbox._010_smoke_user_defined_linters.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.sandbox/org.mpsqa.lint.generic.sandbox.msd, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.behavior_aspect.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.build_scripts.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.constraint_aspect.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.expressions.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.generator_aspect.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.performance_editor.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.performance_typesystem.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.performance_typesystem_rules.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.structure_aspect.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.tests.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.typesystem_aspect.mps
This PR is a prerequisite for the next PR that will follow.  
The UI was polished and there are now different kinds of checks: generic, module, model, root node and node checks which all have different parameters and return type. The old kind of check is the generic check:
Exceptions are now handled by default by the linter itself. You can still handle it yourself and/or forward the message to the results and the error log with the new `forwardException` expression:
=> Linters: Small improvements + separate checks into different categories

code/languages/org.mpsqa.base/solutions/org.mpsqa.base.errors_suppressor.pluginSolution/models/org.mpsqa.base.errors_suppressor.pluginSolution.plugin.mps
The problem is, that a lot of error messages are not normalized. The current fix enforces this before doing the actual regex matching.
Fixes #187
=> errors_suppressors.plugin: ensure error messages are normalized

code/languages/org.mpsqa.base/languages/org.mpsqa.base.errors_suppressor/models/org.mpsqa.base.errors_suppressor.editor.mps, code/languages/org.mpsqa.base/languages/org.mpsqa.base.errors_suppressor/models/org.mpsqa.base.errors_suppressor.structure.mps, code/languages/org.mpsqa.base/solutions/org.mpsqa.base.build/models/org.mpsqa.base.build.mps, code/languages/org.mpsqa.base/solutions/org.mpsqa.base.errors_suppressor.pluginSolution/models/org.mpsqa.base.errors_suppressor.pluginSolution.plugin.mps, code/languages/org.mpsqa.base/solutions/org.mpsqa.base.errors_suppressor.pluginSolution/org.mpsqa.base.errors_suppressor.pluginSolution.msd
- fixes [https://github.com/mbeddr/mps-qa/issues/191](https://github.com/mbeddr/mps-qa/issues/191)
- The feature can be deactivated for every single checking result suppressor config through setting `don't suppress in editor` to true.
=> error suppressor:  also suppress messages in the editor

build.gradle, code/languages/org.mpsqa.testing/languages/org.mpsqa.testcov.buildIntegration.jacoco/generator/templates/org.mpsqa.testcov.buildIntegration.jacoco.generator.templates@generator.mps, code/languages/org.mpsqa.testing/languages/org.mpsqa.testcov.buildIntegration.jacoco/models/org.mpsqa.testcov.buildIntegration.jacoco.behavior.mps, code/languages/org.mpsqa.testing/languages/org.mpsqa.testcov.buildIntegration.jacoco/models/org.mpsqa.testcov.buildIntegration.jacoco.editor.mps, code/languages/org.mpsqa.testing/languages/org.mpsqa.testcov.buildIntegration.jacoco/models/org.mpsqa.testcov.buildIntegration.jacoco.structure.mps, code/languages/org.mpsqa.testing/languages/org.mpsqa.testcov.buildIntegration.jacoco/org.mpsqa.testcov.buildIntegration.jacoco.mpl, code/languages/org.mpsqa.testing/sandbox/build.xml, code/languages/org.mpsqa.testing/sandbox/jacoco.sandbox.build/models/jacoco.sandbox.build.mps, code/languages/org.mpsqa.testing/solutions/org.mpsqa.testing.build/models/org.mpsqa.testing.build.mps
Provide a configuration parameter to set the test reports output directory for 'test modules with coverage'. The default is changed and is now `${build.dir}/test-reports/<test-suite-name>`. This is the reason for designating this change as breaking.
The change works around [MPS-37708](https://youtrack.jetbrains.com/issue/MPS-37708/launchtests-should-write-the-XML-report-into-the-correct-place-right-away). In the built-in 'test modules' aspect, the `<launchtests>` task first writes test reports into a designated directory and then copies them to the requested location. However, the copy will not happen if tests fail and `haltonfailure` is enabled.
To fix this, 'test modules with coverage' instead configures the `<launchtests>` task with the requested directory directly. However, the …
=> [breaking] Configurable JUnit report directory

code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._080_lint_build.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.behavior.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.editor.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.structure.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.typesystem.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.filesystem.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.meta.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.models.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.modules.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.nodes.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.sandbox/models/org.mpsqa.lint.generic.sandbox._010_smoke_user_defined_linters.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.sandbox/org.mpsqa.lint.generic.sandbox.msd, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.behavior_aspect.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.build_scripts.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.performance_editor.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.performance_typesystem.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.performance_utils.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.structure_aspect.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.tests.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.typesystem_aspect.mps
This is a follow-up of https://github.com/mbeddr/mps-qa/pull/184 where a forgot to adapt the saved messages and I also fixed a few linters where the error reporting was missing information. With this new change, you can also navigate in the checker results to files, nodes, models and modules. Files can now be returned as a result in linters.
=> mpsqa.lint: add back missing location information to saved results

code/languages/org.mpsqa.arch/languages/org.mpsqa.arch/models/org.mpsqa.arch.behavior.mps, code/languages/org.mpsqa.arch/languages/org.mpsqa.arch/models/org.mpsqa.arch.constraints.mps, code/languages/org.mpsqa.arch/languages/org.mpsqa.arch/models/org.mpsqa.arch.editor.mps, code/languages/org.mpsqa.arch/languages/org.mpsqa.arch/models/org.mpsqa.arch.intentions.mps, code/languages/org.mpsqa.arch/languages/org.mpsqa.arch/models/org.mpsqa.arch.structure.mps, code/languages/org.mpsqa.arch/languages/org.mpsqa.arch/models/org.mpsqa.arch.typesystem.mps, code/languages/org.mpsqa.arch/languages/org.mpsqa.arch/models/org.mpsqa.arch.util.mps, code/languages/org.mpsqa.arch/languages/org.mpsqa.arch/org.mpsqa.arch.mpl, code/languages/org.mpsqa.arch/solutions/org.mpsqa.arch.pluginSolution/models/org.mpsqa.arch.pluginSolution.plugin.mps, code/languages/org.mpsqa.arch/solutions/org.mpsqa.arch.pluginSolution/org.mpsqa.arch.pluginSolution.msd, code/languages/org.mpsqa.arch/solutions/test.org.mpsqa.arch/models/test.org.mpsqa.arch._010_simple_dependencies@tests.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._060_arch_build.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._080_lint_build.mps
I called those disallowed dependencies "decouplings". Not sure if this is the right term. I had a hard time with the used terms in this language anyway. Please tell me if I replaced an official term somewhere.
=> mpsqa.arch: General improvements + support for disallowed dependencies

code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.modules.mps
This PR removes absolute paths to file in the error reporting from the `modules_in_project_directory_on_harddisk_but_not_added_to_project` linter
=> Fix module / model path in linter error reporting

code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.modules.mps
This PR is a quick fix that removes the location from the reported error. This avoid incompatible whitelists between platforms, and breaking the location link when using the relative paths
=> Remove location in modules_in_project_directory_on_harddisk_but_not_added_to_project linter

code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.modules.mps
This PR improves usability of modules_in_project_directory_on_harddisk_but_not_added_to_project
- remove root directory name entirely from linter
- use path regex pattern to include
=> Improve usability of modules_in_project_directory_on_harddisk_but_not_added_to_project linter

build.gradle, build/scripts/build_all_scripts.xml, code/languages/org.mpsqa.arch/.mps/libraries.xml, code/languages/org.mpsqa.arch/languages/org.mpsqa.arch/models/org.mpsqa.arch.editor.mps, code/languages/org.mpsqa.arch/languages/org.mpsqa.arch/models/org.mpsqa.arch.util.mps, code/languages/org.mpsqa.arch/languages/org.mpsqa.arch/org.mpsqa.arch.mpl, code/languages/org.mpsqa.arch/solutions/org.mpsqa.arch.sandbox/models/org.mpsqa.arch.sandbox.smoke.mps, code/languages/org.mpsqa.base/solutions/org.mpsqa.base.build/models/org.mpsqa.base.build.mps, code/languages/org.mpsqa.base/solutions/org.mpsqa.base.utils/models/org.mpsqa.base.utils.project.mps, code/languages/org.mpsqa.base/solutions/org.mpsqa.base.utils/org.mpsqa.base.utils.msd, code/languages/org.mpsqa.build/solutions/org.mpsqa.build.allScripts/models/org.mpsqa.build.allScripts.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._060_arch_build.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._070_deprecated_build.mps, code/languages/org.mpsqa.build/solutions/org.mpsqa.build/models/org.mpsqa.build._080_lint_build.mps, code/languages/org.mpsqa.deprecated/.mps/libraries.xml, code/languages/org.mpsqa.deprecated/languages/org.mpsqa.deprecated/models/org.mpsqa.deprecated.typesystem.mps, code/languages/org.mpsqa.deprecated/languages/org.mpsqa.deprecated/org.mpsqa.deprecated.mpl, code/languages/org.mpsqa.lint/.mps/libraries.xml, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.behavior.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/models/org.mpsqa.lint.generic.typesystem.mps, code/languages/org.mpsqa.lint/languages/org.mpsqa.lint.generic/org.mpsqa.lint.generic.mpl, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.build/models/org.mpsqa.lint.build.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.build/org.mpsqa.lint.build.msd, code/languages/org.mpsqa.profile/.mps/libraries.xml, code/languages/org.mpsqa.unused/.mps/libraries.xml
- enhanced arch editor with tooltips for module references
- better and centralized utility to access to projects
=> enhance arch editor

build.gradle
Otherwise, dependent projects will try to download the dependencies. This is an issue because `net.sf.jtreemap:ktreemap:1.1.0-atlassian-01` doesn't come from the public maven central repository.
=> Mark dependencies as provided in the build script

code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.generic.linters_library/models/org.mpsqa.lint.generic.linters_library.models.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.libraries_use.mps, code/languages/org.mpsqa.lint/solutions/org.mpsqa.lint.mps_lang.linters_library/models/org.mpsqa.lint.mps_lang.linters_library.performance_constraints.mps
- fixes https://github.com/mbeddr/mps-qa/issues/364
- added "library_classes_from_a_package_always_use_the_same_module" to check that certain used library classes should be available in certain modules
=> bugfix/fix models_in_same_project_with_same_IDs linter, add a linter for checking the use of APIs only from a certain module
